name: superapp check build

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Go
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
        
      - name: build

        run: go get -u all
        run: go build -v ./...
      
      - name: test
        run: go test -v ./...
